
FIND_PATH(HELLO_INCLUDE_DIR hello.h /home/supdev/work/cmakestudy/installdir/include/hello)

FIND_LIBRARY(HELLO_LIBRARY NAMES hello PATH /home/supdev/work/cmakestudy/installdir/lib)

IF( HELLO_INCLUDE_DIR AND HELLO_LIBRARY )
SET(HELLO_FOUND TRUE)
ENDIF(HELLO_INCLUDE_DIR  AND HELLO_LIBRARY)
IF( HELLO_FOUND)
 IF( NOT HELLO_FOUND_QUIETLY )
  MESSAGE(STATUS "Found Hello :${HELLO_LIBRARY}")
 ENDIF(NOT HELLO_FIND_QUIETLY)
ELSE(HELLO_FOUND)
 IF(HELLO_FIND_REQUIRED)
  MESSAGE(FATA_ERROR "Could not find hello library")
 ENDIF(HELLO_FIND_REQUIRED)
ENDIF(HELLO_FOUND)
